name: Scrape Lotto Sanook (HTTP)

on:
  workflow_dispatch: {}
  # schedule:
  #  - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci || npm i

      - name: Run scraper
        run: npm run scrape

      - name: List changes
        run: |
          ls -la data || true
          git status
          git diff -- data || true

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          git commit -m "update lotto from Sanook (HTTP scraper)" || echo "No changes"
          git push
